// This file has been auto generated. 
// Please don't make any changes.
package org.solyton.solawi.bid.application.data.env

import lib.optics.Lensify
import lib.optics.ReadOnly
import lib.optics.lens.Lens
import org.solyton.solawi.bid.application.api.Api

/**
 * Autogenerated class
 */
@Lensify data class Environment(
    @ReadOnly val type: String = "DEV",
    @ReadOnly val backendUrl: String = "localhost:8081",
)

/**
 * Autogenerated ReadOnly Lens.
 * Read [Environment.type]
 */
 @ReadOnly val type: Lens<Environment, String> by lazy{ Lens(
    get = {whole -> whole.type},
    set = {{it}}
) }
/**
 * Autogenerated ReadOnly Lens.
 * Read [Environment.backendUrl]
 */
 @ReadOnly val backendUrl: Lens<Environment, String> by lazy{ Lens(
    get = {whole -> whole.backendUrl},
    set = {{it}}
) }
