package org.solyton.solawi.bid.module.bid.routing.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.db.schema.SearchBidders

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Wed Mar 05 16:39:40 CET 2025
 *
 * Description: ...
 */
class Migration1741189180989(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1741189180989

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(SearchBidders)
    }

    /**
     * Downwards migration (inverse to the upward migration).
     * These migrations are not taken into account by now!
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}