package org.solyton.solawi.bid.module.bid.routing.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.jetbrains.exposed.sql.insert
import org.solyton.solawi.bid.module.db.schema.*

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Thu Oct 31 11:57:50 CET 2024
 *
 * Description: ...
 */
class Migration1730372270554(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1730372270554

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(
            Auctions,
            Rounds,
            BidRounds,
            Bidders,
            AuctionBidders
        )
        // db setup
        // create an auction
        val auction = Auction.new {
            name = "TestAuction"
        }
        // create a round in the auction
        // note: state is "OPENED" by default.
        val round = Round.new {
            this.auction = auction
            link = "test-link"
            //state = RoundState.Started.toString()
        }
        auction.rounds+round
        // invite bidders to the auction
        val bidder = Bidder.new {
            username = "test-user"
            weblingId = 1
            numberOfParts = 1
        }
        AuctionBidders.insert{
            it[AuctionBidders.auctionId] = auction.id
            it[AuctionBidders.bidderId] = bidder.id
        }
        auction.bidders+bidder

    }

    /**
     * Downwards migration (inverse to the upward migration).
     * These migrations are not taken into account by now!
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}