package org.solyton.solawi.bid.module.bid.routing.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database

/**
 * Autogenerated [List] of [Migration]s. Alter with care!
 */
val bidRoutingMigrations: ArrayList<Database.()-> Migration> by lazy{
    arrayListOf<Database.()-> Migration>(
        {Migration1734880481636(this)},
        //{ Migration1729880480552(this) },
        { Migration1730372270554(this) },
        { Migration1741189180989(this) }
    )
}
