package org.solyton.solawi.bid.module.bid.routing.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.db.schema.AuctionDetailsSolawiTuebingenTable
import org.solyton.solawi.bid.module.db.schema.AuctionType
import org.solyton.solawi.bid.module.db.schema.AuctionTypes
import org.solyton.solawi.bid.module.db.schema.BidderDetailsSolawiTuebingenTable

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Sun Dec 22 16:14:41 CET 2024
 *
 * Description:
 * Test-Migration used by int the bid-module
 * - Adds tables:
 *   - AuctionTypes,
 *   - AuctionDetailsSolawiTuebingenTable,
 *   - BidderDetailsSolawiTuebingenTable
 */
class Migration1734880481636(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1734880481636

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(
            AuctionTypes,
            AuctionDetailsSolawiTuebingenTable,
            BidderDetailsSolawiTuebingenTable
        )


    }

    /**
     * Downwards migration (inverse to the upward migration).
     * These migrations are not taken into account by now!
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
