// This file has been partially auto generated. 
// Please don't make any changes to the lenses.
// Feel free to add or remove annotated properties from
// the generator data class. The corresponding lenses 
// will be removed or added on the next run of the 
// lens generator. See below for more details.
package org.solyton.solawi.bid.module.navbar.data

import org.evoleq.optics.Lensify
import org.evoleq.optics.ReadOnly
import org.evoleq.optics.ReadWrite
import org.evoleq.optics.lens.Lens
import org.solyton.solawi.bid.application.data.env.Environment
import org.solyton.solawi.bid.module.i18n.data.I18N

/**
 * Generator class.
 * Feel free to add or remove annotated properties from
 * the class. Make sure that they are annotated with
 * - @ReadOnly
 * - @ReadWrite
 * If you want that a property-lens will be generated
 * on the next run of the lens generator.
 * If not, just omit the annotation or annotate it with @Ignore.
 */
@Lensify data class NavBar(
    @ReadWrite val i18n: I18N,
    @ReadOnly val environment: Environment
)

/**
 * Autogenerated Lens.
 * Read and manipulate [NavBar.i18n]
 */
@ReadWrite val i18n: Lens<NavBar, I18N> by lazy{ Lens(
    get = {whole -> whole.i18n},
    set = {part -> {whole -> whole.copy(i18n = part)}}
) }
/**
 * Autogenerated Setter of a Pseudo Lens
 * Manipulate [NavBar.i18n]
 */
@ReadWrite fun NavBar.i18n(set: I18N.()->I18N ): NavBar = copy(i18n = set(i18n)) 
/**
 * Autogenerated ReadOnly Lens.
 * Read [NavBar.environment]
 */
@ReadOnly val environment: Lens<NavBar, Environment> by lazy{ Lens(
    get = {whole -> whole.environment},
    set = {{it}}
) }
