// This file has been auto generated. 
// Please don't make any changes.
package org.solyton.solawi.bid.module.i18n.data

import org.evoleq.language.Lang
import org.evoleq.optics.Lensify
import org.evoleq.optics.ReadWrite
import org.evoleq.optics.lens.Lens

/**
 * Autogenerated class
 */
@Lensify data class I18N(
    @ReadWrite val locale: String = "de",
    @ReadWrite val locales: List<String> = listOf(),
    @ReadWrite val language: Lang = Lang.Block("", listOf()),
)

/**
 * Autogenerated Lens.
 * Read and manipulate [I18N.locale]
 */
 @ReadWrite val locale: Lens<I18N, String> by lazy{ Lens(
    get = {whole -> whole.locale},
    set = {part -> {whole -> whole.copy(locale = part)}}
) }
/**
 * Autogenerated Lens.
 * Read and manipulate [I18N.locales]
 */
 @ReadWrite val locales: Lens<I18N, List<String>> by lazy{ Lens(
    get = {whole -> whole.locales},
    set = {part -> {whole -> whole.copy(locales = part)}}
) }
/**
 * Autogenerated Lens.
 * Read and manipulate [I18N.language]
 */
 @ReadWrite val language: Lens<I18N, Lang> by lazy{ Lens(
    get = {whole -> whole.language},
    set = {part -> {whole -> whole.copy(language = part)}}
) }
