// This file has been partially auto generated. 
// Please don't make any changes to the lenses.
// Feel free to add or remove annotated properties from
// the generator data class. The corresponding lenses 
// will be removed or added on the next run of the 
// lens generator. See below for more details.
package org.solyton.solawi.bid.application.data

import kotlinx.coroutines.flow.MutableSharedFlow
import org.evoleq.compose.modal.Modals
import org.evoleq.ktorx.api.Api
import org.evoleq.optics.Lensify
import org.evoleq.optics.ReadOnly
import org.evoleq.optics.ReadWrite
import org.evoleq.optics.lens.Lens
import org.evoleq.optics.storage.Action
import org.solyton.solawi.bid.api.solawiApi
import org.solyton.solawi.bid.application.data.env.Environment
import org.solyton.solawi.bid.module.bid.data.Auction
import org.solyton.solawi.bid.module.cookie.data.CookieDisclaimer
import org.solyton.solawi.bid.module.i18n.data.I18N
import org.solyton.solawi.bid.module.user.User

/**
 * Generator class.
 * Feel free to add or remove annotated properties from
 * the class. Make sure that they are annotated with
 * - @ReadOnly
 * - @ReadWrite
 * If you want that a property-lens will be generated
 * on the next run of the lens generator.
 * If not, just omit the annotation or annotate it with @Ignore.
 */
@Lensify data class Application (
    @ReadOnly val environment: Environment,
    @ReadOnly val api: Api = solawiApi,
    @ReadOnly val actions: MutableSharedFlow<Action<Application, *, *>> = MutableSharedFlow(),
    @ReadWrite val modals: Modals<Int> = mapOf(),
    @ReadWrite val i18N: I18N = I18N(),
    @ReadWrite val userData: User = User("","","",""),
    @ReadWrite val cookieDisclaimer: CookieDisclaimer = CookieDisclaimer(),
    @ReadWrite val auctions: List<Auction> = listOf()
)

/**
 * Autogenerated ReadOnly Lens.
 * Read [Application.environment]
 */
@ReadOnly val environment: Lens<Application, Environment> by lazy{ Lens(
    get = {whole -> whole.environment},
    set = {{it}}
) }
/**
 * Autogenerated ReadOnly Lens.
 * Read [Application.api]
 */
@ReadOnly val api: Lens<Application, Api> by lazy{ Lens(
    get = {whole -> whole.api},
    set = {{it}}
) }
/**
 * Autogenerated ReadOnly Lens.
 * Read [Application.actions]
 */
@ReadOnly val actions: Lens<Application, MutableSharedFlow<Action<Application, *,*>>> by lazy{ Lens(
    get = {whole -> whole.actions},
    set = {{it}}
) }
/**
 * Autogenerated Lens.
 * Read and manipulate [Application.modals]
 */
@ReadWrite val modals: Lens<Application, Modals<Int>> by lazy{ Lens(
    get = {whole -> whole.modals},
    set = {part -> {whole -> whole.copy(modals = part)}}
) }
/**
 * Autogenerated Setter of a Pseudo Lens
 * Manipulate [Application.modals]
 */
@ReadWrite fun Application.modals(set: Modals<Int>.()->Modals<Int> ): Application = copy(modals = set(modals)) 
/**
 * Autogenerated Lens.
 * Read and manipulate [Application.i18N]
 */
@ReadWrite val i18N: Lens<Application, I18N> by lazy{ Lens(
    get = {whole -> whole.i18N},
    set = {part -> {whole -> whole.copy(i18N = part)}}
) }
/**
 * Autogenerated Setter of a Pseudo Lens
 * Manipulate [Application.i18N]
 */
@ReadWrite fun Application.i18N(set: I18N.()->I18N ): Application = copy(i18N = set(i18N)) 
/**
 * Autogenerated Lens.
 * Read and manipulate [Application.cookieDisclaimer]
 */
@ReadWrite val cookieDisclaimer: Lens<Application, CookieDisclaimer> by lazy{ Lens(
    get = {whole -> whole.cookieDisclaimer},
    set = {part -> {whole -> whole.copy(cookieDisclaimer = part)}}
) }
/**
 * Autogenerated Setter of a Pseudo Lens
 * Manipulate [Application.cookieDisclaimer]
 */
@ReadWrite fun Application.cookieDisclaimer(set: CookieDisclaimer.()->CookieDisclaimer ): Application = copy(cookieDisclaimer = set(cookieDisclaimer)) 
/**
 * Autogenerated Lens.
 * Read and manipulate [Application.userData]
 */
@ReadWrite val userData: Lens<Application, User> by lazy{ Lens(
    get = {whole -> whole.userData},
    set = {part -> {whole -> whole.copy(userData = part)}}
) }
/**
 * Autogenerated Setter of a Pseudo Lens
 * Manipulate [Application.userData]
 */
@ReadWrite fun Application.userData(set: User.()->User ): Application = copy(userData = set(userData)) 
/**
 * Autogenerated Lens.
 * Read and manipulate [Application.auctions]
 */
@ReadWrite val auctions: Lens<Application, List<Auction>> by lazy{ Lens(
    get = {whole -> whole.auctions},
    set = {part -> {whole -> whole.copy(auctions = part)}}
) }
/**
 * Autogenerated Setter of a Pseudo Lens
 * Manipulate [Application.auctions]
 */
@ReadWrite fun Application.auctions(set: List<Auction>.()->List<Auction> ): Application = copy(auctions = set(auctions)) 
