// This file has been auto generated. 
// Please don't make any changes.
package org.solyton.solawi.bid.application.data

import org.evoleq.optics.Lensify
import org.evoleq.optics.ReadOnly
import org.evoleq.optics.ReadWrite
import org.evoleq.compose.modal.Modals
import org.evoleq.ktorx.api.Api
import org.evoleq.optics.lens.Lens
import org.solyton.solawi.bid.api.solawiApi
import org.solyton.solawi.bid.module.user.User
import org.solyton.solawi.bid.application.data.env.Environment
import org.solyton.solawi.bid.application.data.i18n.I18N

/**
 * Autogenerated class
 */
@Lensify data class Application (
    @ReadOnly val environment: Environment,
    @ReadOnly val api: Api = solawiApi,
    @ReadWrite val modals: Modals<Int> = mapOf(),
    @ReadWrite val isCookieDisclaimerConfirmed: Boolean = false,
    @ReadWrite val i18N: I18N = I18N(),
    @ReadWrite val userData: User = User("","","",""),
)

/**
 * Autogenerated ReadOnly Lens.
 * Read [Application.environment]
 */
 @ReadOnly val environment: Lens<Application, Environment> by lazy{ Lens(
    get = {whole -> whole.environment},
    set = {{it}}
) }
/**
 * Autogenerated ReadOnly Lens.
 * Read [Application.api]
 */
 @ReadOnly val api: Lens<Application, Api> by lazy{ Lens(
    get = {whole -> whole.api},
    set = {{it}}
) }
/**
 * Autogenerated Lens.
 * Read and manipulate [Application.userData]
 */
 @ReadWrite val userData: Lens<Application, User> by lazy{ Lens(
    get = {whole -> whole.userData},
    set = {part -> {whole -> whole.copy(userData = part)}}
) }
/**
 * Autogenerated Lens.
 * Read and manipulate [Application.modals]
 */
 @ReadWrite val modals: Lens<Application, Modals<Int>> by lazy{ Lens(
    get = {whole -> whole.modals},
    set = {part -> {whole -> whole.copy(modals = part)}}
) }
/**
 * Autogenerated Lens.
 * Read and manipulate [Application.isCookieDisclaimerConfirmed]
 */
 @ReadWrite val isCookieDisclaimerConfirmed: Lens<Application, Boolean> by lazy{ Lens(
    get = {whole -> whole.isCookieDisclaimerConfirmed},
    set = {part -> {whole -> whole.copy(isCookieDisclaimerConfirmed = part)}}
) }
