// This file has been auto generated. 
// Please don't make any changes.
package org.solyton.solawi.bid.application.data

import lib.optics.Lensify
import lib.optics.ReadOnly
import lib.optics.ReadWrite
import lib.optics.lens.Lens
import org.solyton.solawi.bid.application.data.env.Environment
import org.solyton.solawi.bid.module.user.User

/**
 * Autogenerated class
 */
@Lensify
data class Application (
    @ReadOnly val environment: Environment,
    @ReadWrite val userData: User
)

/**
 * Autogenerated ReadOnly Lens.
 * Read [Application.environment]
 */
 @ReadOnly
val environment: Lens<Application, Environment> by lazy{ Lens(
    get = {whole -> whole.environment},
    set = {{it}}
) }
/**
 * Autogenerated Lens.
 * Read and manipulate [Application.userData]
 */
 @ReadWrite
val userData: Lens<Application, User> by lazy{ Lens(
    get = {whole -> whole.userData},
    set = {part -> {whole -> whole.copy(userData = part)}}
) }
