package org.solyton.solawi.bid.module.db.schema.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Thu Oct 31 10:02:50 CET 2024
 *
 * Description: ...
 */
class Migration1730365370722(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1730365370722

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        TODO("Not yet implemented")
    }

    /**
     * Downwards migration (inverse to the upward migration).
     * These migrations are not taken into account by now!
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}