package org.solyton.solawi.bid.module.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.application.permission.Context
import org.solyton.solawi.bid.module.db.repository.addChild
import org.solyton.solawi.bid.module.db.schema.ContextEntity
import org.solyton.solawi.bid.module.db.schema.ContextsTable

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Fri Apr 04 19:11:20 CEST 2025
 *
 * Description: Create Contexts:
 * 1. Application Organization Context
 */
class Migration1743786680319(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1743786680319

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val applicationContext = ContextEntity.find { ContextsTable.name eq Context.Application.value }.first()

        val applicationOrganizationContext = ContextEntity.find { ContextsTable.name eq Context.Application.Organization.value }.firstOrNull()

        if(applicationOrganizationContext != null) {
            applicationOrganizationContext.name = Context.Organization.value
            //applicationContext.addChild(applicationOrganizationContext)
        }

    }

    /**
     * Downwards migration (inverse to the upward migration).
     * These migrations are not taken into account by now!
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}