package org.solyton.solawi.bid.module.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.db.repository.createRootOrganization
import org.solyton.solawi.bid.module.db.schema.*

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Thu Jan 16 15:35:45 CET 2025
 *
 * Description: Create Organization Solawi Tübingen 2.0
 */
class Migration1737038145921(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1737038145921

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        val user = UserEntity.find{
            Users.username eq "schmidt@alpha-structure.com"
        }.first()
        val userProfile = UserProfile.new {
            this.user = user
        }



        val solawi = createRootOrganization("Solawi Tübingen 2.0", user)

        val who = DistributionPointEntity.new {
            name = "WHO"
            organization = solawi
        }
        val dusslingen = DistributionPointEntity.new {
            name = "Dusslingen"
            organization = solawi
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     * These migrations are not taken into account by now!
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}