package org.solyton.solawi.bid.module.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.db.schema.*

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Sun Dec 22 15:27:31 CET 2024
 *
 * Description:
 * Add tables to distinguish Auction Types
 * - AuctionTypes,
 * - AuctionDetailsSolawiTuebingenTable,
 * - BidderDetailsSolawiTuebingenTable
 */
class Migration1734877651652(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1734877651652

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(
            AuctionTypes,
            AuctionDetailsSolawiTuebingenTable,
            BidderDetailsSolawiTuebingenTable
        )

        // var solawiTuebingenAuctionType =
        AuctionType.new {
            type = "SOLAWI_TUEBINGEN"
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     * These migrations are not taken into account by now!
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
