package org.solyton.solawi.bid.module.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.Transaction
import org.jetbrains.exposed.sql.insert
import org.solyton.solawi.bid.module.db.schema.AcceptedRoundEntity
import org.solyton.solawi.bid.module.db.schema.AcceptedRoundsTable
import org.solyton.solawi.bid.module.db.schema.AuctionEntity
import org.solyton.solawi.bid.module.db.schema.RoundEntity
import java.util.UUID

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Wed Mar 19 17:20:23 CET 2025
 *
 * Description: Add accepted round
 */
class Migration1742401223055(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1742401223055

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {

        val auction = AuctionEntity.findById(UUID.fromString("bbadd2c5-9b14-4714-9ccb-c6f0a599834d"))
        val round = RoundEntity.findById(UUID.fromString("edc429ee-8181-4401-bc8c-d0fb3504b6f3"))

        if(auction == null || round == null) return@up

        AcceptedRoundEntity.new {
            this.auction = auction
            this.round = round
        }
    }

    /**
     * Downwards migration (inverse to the upward migration).
     * These migrations are not taken into account by now!
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
