package org.solyton.solawi.bid.module.db.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database

/**
 * Autogenerated [List] of [Migration]s. Alter with care!
 */
val dbMigrations: ArrayList<Database.()-> Migration> by lazy{
    arrayListOf<Database.()-> Migration>(
        { Migration1712001749830(this) },
        { Migration1730143239225(this) },
        { Migration1731853772782(this) },
        { Migration1731854081411(this) },
        { Migration1734877651652(this) },
        { Migration1735334305003(this) },
        { Migration1737038145921(this) }
    )
}