name: Build Frontend and Test
description: Build frontend and run all tests
runs:
  using: composite
  steps:
    - name: Check changes
      id: changes
      uses: dorny/paths-filter@v3
      with:
        filters: |
          frontend:
             - "solawi-bid-frontend/**"
             - "solawi-bid-api-data/**"
             - ".github/**"
             - "gradle" 

    - name: Build frontend without tests
      shell: bash
      run: ./gradlew solawi-bid-frontend:build -x test
      if: steps.changes.outputs.frontend == 'true'
    - name: Run tests
      shell: bash
      run: ./gradlew solawi-bid-frontend:jsBrowserTest # -x build
      if: steps.changes.outputs.frontend == 'true'
    - name: Upload js test report
      uses: actions/upload-artifact@v4
      with:
        name: JS-Test-Report
        path: solawi-bid-frontend/build/test-results/jsBrowserTest
      if: steps.changes.outputs.frontend == 'true'
    - name: Upload ${{inputs.reportName}} test results
      uses: dorny/test-reporter@v2
      with:
        name: JS Test Results
        artifact: JS-Test-Report
        path: "*.xml"
        reporter: java-junit
        badge-title: JsTests
      if: steps.changes.outputs.frontend == 'true'