// This file has been auto generated. 
// Please don't make any changes.
package org.solyton.solawi.bid.module.user

import lib.optics.Lensify
import lib.optics.ReadWrite
import lib.optics.lens.Lens
import org.solyton.solawi.bid.module.authentication.data.api.RefreshToken

/**
 * Autogenerated class
 */
@Lensify
data class User(
    @ReadWrite val username: String,
    @ReadWrite val password: String,
    @ReadWrite val javaWebToken: String,
    @ReadWrite val refreshToken: String
)

/**
 * Autogenerated Lens.
 * Read and manipulate [User.username]
 */
 @ReadWrite
val username: Lens<User, String> by lazy{ Lens(
    get = {whole -> whole.username},
    set = {part -> {whole -> whole.copy(username = part)}}
) }
/**
 * Autogenerated Lens.
 * Read and manipulate [User.password]
 */
 @ReadWrite
val password: Lens<User, String> by lazy{ Lens(
    get = {whole -> whole.password},
    set = {part -> {whole -> whole.copy(password = part)}}
) }
/**
 * Autogenerated Lens.
 * Read and manipulate [User.javaWebToken]
 */
 @ReadWrite
val javaWebToken: Lens<User, String> by lazy{ Lens(
    get = {whole -> whole.javaWebToken},
    set = {part -> {whole -> whole.copy(javaWebToken = part)}}
) }
/**
 * Autogenerated Lens.
 * Read and manipulate [User.refreshToken]
 */
 @ReadWrite
val refreshToken: Lens<User, String> by lazy{ Lens(
    get = {whole -> whole.refreshToken},
    set = {part -> {whole -> whole.copy(refreshToken = part)}}
) }
