package org.solyton.solawi.bid.module.authentication.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.Transaction
import org.solyton.solawi.bid.module.db.schema.Tokens
import org.solyton.solawi.bid.module.db.schema.User
import org.solyton.solawi.bid.module.db.schema.Users

/**
 * Autogenerated [Migration],
 * generated by the evoleq/exposedx migration gradle-plugin.
 * Alter with care!
 *
 * Generated at Thu Oct 31 11:57:50 CET 2024
 *
 * Description: ...
 */
class Migration1730372270555(
    override val database: Database
) : Migration {

    /**
     * Id of the migration, do not change!
     */
    override val id: Long
        get() = 1730372270555

    /**
     * Upwards migration
     */
    override suspend fun Transaction.up() {
        SchemaUtils.create(
            Users,
            Tokens,
            /*
            Auctions,
            Rounds,
            BidRounds,
            Bidders,
            AuctionBidders

             */
        )
        // val smith =
        User.new {
            username = "developer@alpha-structure.com"
            password = "$2a$10$5EENEnXKE4oNT0AejWzy8Oa09DkBDiQTnk2LyqtqpBa3DrZijo51O"
        }
        commit()
    }

    /**
     * Downwards migration (inverse to the upward migration).
     * These migrations are not taken into account by now!
     */
    override suspend fun Database.down() {
        TODO("Not yet implemented")
    }
}
