package org.solyton.solawi.bid.module.authentication.migrations

import org.evoleq.exposedx.migrations.Migration
import org.jetbrains.exposed.sql.Database

/**
 * Autogenerated [List] of [Migration]s. Alter with care!
 */
val authenticationMigrations: ArrayList<Database.()-> Migration> by lazy{
    arrayListOf<Database.()-> Migration>(
        { Migration1730372270555(this) },
        { Migration1734880566274(this) }
    )
}